language: android

notifications:
    email: true
        recipients:
            - 1181830457@qq.com

# open Travis CI task
sudo: false

android:
    components:
      - tools
      - platform-tools
      - build-tools-25.0.2
      - android-25
      - extra-google-m2repository
      - extra-android-m2repository
      - extra-android-support

    licenses:
      - 'Apache 2.0'
      - 'android-sdk-license-.+'

jdk:
    - oraclejdk8

# Emulator Management: Create, Start and Wait
before_script:
    - chmod +x gradlew
#    - echo no | android create avd --force -n test -t android-25 --abi armabi-v7a
#    - emulator -avd test -no-audio -no-window &
#    - android-wait-for-emulator
#    - adb shell input keyenvent 82 &
#    - ./gradlew clean build uploadArchives --info

script:
#    - ./gradlew assembleRelease
    - ./gradlew -q -s -Dscan -PbuildInfo.build.number=$TRAVIS_BUILD_NUMBER -PbuildInfo.buildUrl=https://travis-ci.org/${TRAVIS_REPO_SLUG}/builds/${TRAVIS_JOB_ID} -PbuildInfo.buildAgent.name=$USER -PbuildInfo.principal=$USER --debug --info clean assemble check fullTest artifactoryPublish

# clean
before_cache:
    - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
    directories:
        - $HOME/.gradle/caches/
        - $HOME/.gradle/wrapper/

# install deploy
before_deploy:
    - mv app/build/outputs/apk-release.apk app/build/outputs/apk/threeline.apk

# deploy to github release
deploy:
    provider: release
    api_key:
        secure:[0594fd1304d056c08486962cb7e0fec476d26d60]
    file: app/build/outputs/apk/threeline.apk
#    must set true, otherwise Travis CI has clean the apk file
    skip_cleanup: true
#    deploy time when set tags is true
    on:
      tags: true

